### ISSUE TITLE
Test application needed 

### ISSUE THREAD

**Issue by chrismrutherford** [openwrt/video#6]
I have been able to build the QT framework on an arm platform however I am missing an example application.  When I try to create a test app qmake has problems with incorrect paths etc  (oh joy).  Please could you create an example application package, maybe just a hello world QT app.  This would be really helpful as it would prove the build process and ensure all paths to qmake includes are correct.

**Comment by axlrose** [comment]
I also encountered the same problem, can not compile their own qt hello world

**Comment by mirko** [comment]
In case almost 4 years later you're still interested: there's the qt5base-examples package (now).
